version: '3'
services:
  postgres:
    image: ${IDEV_IMAGE_PREFIX}/postgres:16
    container_name: ${IDEV_CONTAINER_NAME_PREFIX}-postgres
    restart: always
    privileged: true
    volumes:
      - ./postgres/postgresql:/var/lib/postgresql
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
      TZ: ${IDEV_TZ}
    
    networks:
      - idev-network  # 使用自定义网络