version: "3"
services:
  xxl-job-admin:
    image: ${IDEV_IMAGE_PREFIX}/xuxueli-xxl-job-admin:2.2.0
    container_name: ${IDEV_CONTAINER_NAME_PREFIX}-xxl-job-admin
    restart: always
    privileged: true
    volumes:
      - ./xxjob/logs:/data/applogs
    ports:
      - "${XXLJOB_PORT}:8800"
    environment:
      # 设置启动参数
      PARAMS: >
        --server.port=8800
        --server.servlet.context-path=/xxl-job-admin
        --spring.datasource.url=jdbc:mysql://${XXLJOB_MYSQL_HOST}:${XXLJOB_MYSQL_PORT}/${XXLJOB_MYSQL_DB_NAME}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=${XXLJOB_MYSQL_USERNAME}
        --spring.datasource.password=${XXLJOB_MYSQL_PASSWORD}
        --xxl.job.accessToken=${XXLJOB_ACCESS_TOKEN}
